### see all users
GET http://localhost:3000/users

### create user
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "test",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### session create/login
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}



### get all products
GET http://localhost:3000/products

### get 1 product
GET http://localhost:3000/products/1

### create product
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "test",
  "price": 1,
  "description": "test",
  "supplier_id": 1,
  "quantity": 1
}

### update product
PATCH http://localhost:3000/products/1
Content-Type: application/json

{
  "price": 1,
  "quantity": 2
}

### delete product
DELETE http://localhost:3000/products/6



### get all orders
GET http://localhost:3000/orders

### show order
GET http://localhost:3000/orders/1

### create order
POST http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDI4MTQ2MjZ9.Q4O0C0-UwZR0WVFP44TKKBkt-MfaPkQJhoWwUh3CQt0
Content-Type: application/json

{
  "product_id": 2,
  "quantity": 3,
  "subtotal": 1,
  "tax": 0,
  "total": 1
}