### see all users
GET http://localhost:3000/users

### create user
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "test",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### get all products
GET http://localhost:3000/products

### get 1 product
GET http://localhost:3000/products/1

### create product
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "test",
  "price": 1,
  "description": "test",
  "supplier_id": 1,
  "quantity": 1
}

### update product
PATCH http://localhost:3000/products/4
Content-Type: application/json

{
  "price": 2,
  "quantity": 2
}

### delete product
DELETE http://localhost:3000/products/6
