@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDU1Nzk3Njd9.gUGuUAWX4OpPIzUewmiVXu8Ac06pDVFo9ohdnj9tIVE
@host = https://blooming-mesa-94898.herokuapp.com/
### see all users
GET {{host}}users

### create user
POST {{host}}users
Content-Type: application/json

{
  "name": "test!!",
  "email": "test11@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### session create/login
POST {{host}}sessions
Content-Type: application/json

{
  "email": "test11@test.com",
  "password": "password"
}



### get all products
GET {{host}}products

### get 1 product
GET {{host}}products/1

### create product
POST {{host}}products
Content-Type: application/json

{
  "name": "test",
  "price": 1,
  "description": "test!",
  "supplier_id": 1,
  "quantity": 1
}

### update product
PATCH {{host}}products/4
Content-Type: application/json

{
  "price": 100,
  "quantity": 2
}

### delete product
DELETE {{host}}products/4



### get all orders
GET {{host}}orders
Authorization: Bearer {{jwt}}

### show order
GET {{host}}orders/26
Authorization: Bearer {{jwt}}

### create order
POST {{host}}orders
Authorization: Bearer {{jwt}}
Content-Type: application/json


### get all cart items
GET {{host}}carted_products
Authorization: Bearer {{jwt}}

### create cart item
POST {{host}}carted_products
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "product_id": 3,
  "quantity": 4
}

### delete cart item
DELETE {{host}}carted_products/1
Authorization: Bearer {{jwt}}